import type { Persona } from './supabase';

export function exportPersonaPDF(persona: Persona): void {
  const dateStr = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  const SEP = '━'.repeat(62);
  const THIN = '─'.repeat(62);

  const lines = [
    'CLARIVO PRO',
    'Synthetic Persona Report',
    `Generated on ${dateStr}`,
    '',
    SEP,
    '',
    'DEMOGRAPHICS',
    THIN,
    `  Name             ${persona.name}`,
    `  Age              ${persona.age}`,
    `  Occupation       ${persona.occupation}`,
    `  Location         ${persona.location}`,
    `  Tech Savviness   ${persona.tech_savviness}`,
    '',
    SEP,
    '',
    'PAIN POINTS',
    THIN,
    ...persona.pain_points.map((p, i) => `  ${i + 1}. ${p}`),
    '',
    SEP,
    '',
    'MOTIVATIONS',
    THIN,
    ...persona.motivations.map((m, i) => `  ${i + 1}. ${m}`),
    '',
    SEP,
    '',
    "This is a synthetic persona generated by Clarivo's persona engine.",
    'It does not represent a real individual.',
    '',
  ];

  const content = lines.join('\n');
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);

  const a = document.createElement('a');
  a.href = url;
  a.download = `${persona.name.replace(/\s+/g, '_')}_persona.txt`;
  a.style.display = 'none';
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
